### ISSUE TITLE
Scissor test failure on Mac

### ISSUE THREAD

**Issue by kanthoney** [OoliteProject/oolite#136]
As reported on the BB [here](http://aegidian.org/bb/viewtopic.php?f=3&t=15831&start=570), the scissor test in the short range chart screen fails:

![image](https://cloud.githubusercontent.com/assets/5890866/7516228/b5df182a-f4c5-11e4-9938-d42305f04bbb.png)

The problem appears to be confusion between points and pixels on the Mac retina screen. There is some [deleveloper information](https://developer.apple.com/library/mac/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/CapturingScreenContents/CapturingScreenContents.html#//apple_ref/doc/uid/TP40012302-CH10-SW1) available which may help solve this problem.

**Comment by kanthoney** [comment]
So the Mac retina display is a display where each point on the screen is a square of four pixels.  OpenGL doesn't know about points, so a Mac OpenGL application has two options.  The default "lo-res" option is to request a viewport size based on points and then double everything in both directions to map it to pixels.  The "hi-res" option is to request a viewport size based on pixels instead of points.

What seems to be happening here is that OpenGL is rendering everything, then doubling it up, and *then* applying the scissor test without first doubling the coordinates of the scissor rectangle.  Consequently, it's scissoring the bottom left quarter of the window instead of the whole one.  Could it be a buggy driver?

**Comment by iandol** [comment]
Just to provide screenshot machine context, this is a retina Macbook Pro running the latest public beta of 10.10.4 with up-to-date drivers -- the resolution where the problem happens is 1440x900HiDPI — I can fix it by disabling the HiDPI mode but this causes havoc for other applications (you need special software to disable a HiDPI mode, OS X doesn't allow this normally). Most of the rest of Oolite works fine, and rendering is nice and crisp in HiDPI mode, it doesn't look fuzzy etc.

**Comment by AnotherCommander** [comment]
Kevin, remember the code you had written when you initially implemented the scrolling chart feature? Which was removed soon after we found that the scissor test method does exactly what we wanted but much faster? In case there is no fix to this issue soon, how about re-introducing that code for Mac only and make the game switch to it via an e.g. defaults file setting? I know it is not the perfect fix, but given the absence of our Mac maintainers, maybe this could be a way out of the problem, at the expense of speed of scrolling on retina Macs. What do you think?

**Comment by kanthoney** [comment]
I'm looking at this Mac code in MyOpenGLView.m:

```
- (void) initialiseGLWithSize:(NSSize)v_size
{
        viewSize = v_size;
        if (viewSize.width/viewSize.height > 4.0/3.0) {
                display_z = 480.0 * viewSize.width/viewSize.height;
                x_offset = 240.0 * viewSize.width/viewSize.height;
                y_offset = 240.0;
        } else {
                display_z = 640.0;
                x_offset = 320.0;
                y_offset = 320.0 * viewSize.height/viewSize.width;
        }

        if ([self respondsToSelector:@selector(convertSizeToBacking:)])
        {
                // High resolution mode support.
                v_size = [self convertSizeToBacking:v_size];
        }

        [self openGLContext];   // Force lazy setup if needed.
        [[self gameController] setUpBasicOpenGLStateWithSize:v_size];
        [[self openGLContext] flushBuffer];

        m_glContextInitialized = YES;
}
```

I've got a hunch that if we insert a `[self  setWantsBestResolutionOpenGLSurface:YES];` in the  bit that mentions high resolution support, that may fix the problem.  (It's possible that it'd make the game only use the bottom left hand corner of the screen on retina displays.  I think the fix for that would be to add `viewSize = v_size;` after the `convertSizeToBacking` call.)

It's probably worth trying that before the nasty hack.  I'll look into it a bit more this evening.

**Comment by AnotherCommander** [comment]
@iandol Kevin commited an attempted fix a little while ago. Can you please test tomorow's nightly build and let us know if it has resolved the problem?

**Comment by kanthoney** [comment]
Did we get any build errors?

**Comment by AnotherCommander** [comment]
Unfortunately it looks like the nightly build for Mac is stuck on May 5th. Last revision built was 389e3d4. We really need Mac maintainers to look at this or feedback from iandol, in case he can build the source himself.

**Comment by iandol** [comment]
Sadly I can't build oolite, so I'll have to wait for a new nightly before I can confirm a fix. Thanks for looking at this!!!

**Comment by kanthoney** [comment]
If you want to give it a go (no pressure if you don't), you just need a git client (available *free* from http://git-scm.com/) and xcode (available *free* from the [app store](https://itunes.apple.com/gb/app/xcode/id497799835?mt=12)).

To check out the source code using git, open a command line and run

    git clone https://github.com/OoliteProject/oolite
    cd oolite
    git submodule update --init

(There'll be an equivalent procedure with one of the gui clients, but you'll be on your own with those.)

This will create a folder called `oolite`, with a subfolder `Oolite.xcodeproj`.  If you open the file `project.pbxproj` inside that it should launch xcode, and then (according to the readme, anyway) hit Build.

**Comment by iandol** [comment]
I get the following build errors/warnings:

```
/Users/ian/Code/oolite/src/Core/OOOXZManager.m:781:59: error: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
        OOLog(kOOOXZDebugLog,@"Dependency stack has %u elements",[_dependencyStack count]);
                                                    ~~           ^~~~~~~~~~~~~~~~~~~~~~~~
                                                    %lu
In file included from /Users/ian/Code/oolite/src/Core/OOOXZManager.m:27:
In file included from /Users/ian/Code/oolite/src/Core/OOOXZManager.h:27:
In file included from /Users/ian/Code/oolite/src/Core/OOCocoa.h:261:
/Users/ian/Code/oolite/src/Core/OOLogging.h:88:185: note: expanded from macro 'OOLog'
        #define OOLog(class, format, ...)                               do { if (OOLogWillDisplayMessagesInClass(class)) { OOLogWithFunctionFileAndLine(class, OOLOG_FUNCTION_NAME, OOLOG_FILE_NAME, __LINE__, format, ## __VA_ARGS__); }} while (0)
                                                                                                                                                                                                                          ^
/Users/ian/Code/oolite/src/Core/OOOXZManager.m:848:71: error: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
                                OOLog(kOOOXZDebugLog,@"Dependency stack: installing %u from list",index);
                                                                                    ~~            ^~~~~
                                                                                    %lu
In file included from /Users/ian/Code/oolite/src/Core/OOOXZManager.m:27:
In file included from /Users/ian/Code/oolite/src/Core/OOOXZManager.h:27:
In file included from /Users/ian/Code/oolite/src/Core/OOCocoa.h:261:
/Users/ian/Code/oolite/src/Core/OOLogging.h:88:185: note: expanded from macro 'OOLog'
        #define OOLog(class, format, ...)                               do { if (OOLogWillDisplayMessagesInClass(class)) { OOLogWithFunctionFileAndLine(class, OOLOG_FUNCTION_NAME, OOLOG_FILE_NAME, __LINE__, format, ## __VA_ARGS__); }} while (0)
                                
```

It offered me a chance to auto-fix it which I tried but then I got the following error:\

```
/Users/ian/Code/oolite/src/Core/OOOXZManager.m:848:72: Expected expression
```

**Comment by kanthoney** [comment]
Thanks very much.  I think I've fixed the error, although I've only done what the auto fix probably did.

To fetch the changes, command line again and `cd` to the `oolite` folder.  Then

    git checkout -- .

to clear any changes made by the autofix (notice the `.` at the end), then

    git fetch origin
    git pull origin master

And then try another build.  And again, thanks for your help!

**Comment by iandol** [comment]
So, I clean (⇧⌘K) then I run (⌘R, I also tried building then manually running the app in the Products/ folder) in XCode and no build errors, then I start a new commander in strict mode but I still see this problem :-(
![screen shot 2015-05-11 at 17 00 57](https://cloud.githubusercontent.com/assets/153905/7569495/116d2aae-f801-11e4-8a5d-5b4b6596d0d2.png)

**Comment by iandol** [comment]
Note, I also tried to build oolite - Deployment just in case it was somehow differenrt and got this build error:

````
Debug Bundle Group
/Users/ian/Code/oolite/src/Core/Scripting/OOJSPropID.h
/Users/ian/Code/oolite/src/Core/Scripting/OOJSPropID.h:26:10: 'jsapi.h' file not found
```

**Comment by kanthoney** [comment]
The fix isn't enabled by default, in case it breaks stuff for non-retina users.  To enable it (I'm blagging the instructions from [here](http://wiki.alioth.net/index.php/Hidden_Settings_in_Oolite)), try the following from the command line:

    defaults write org.aegidian.oolite issue_136_fix <value>

where `<value>` is `0` (off), `1` (possible fix no. 1), or `2` (possible fix no. 2)

I'm guessing that the first fix might work, or it might restrict Oolite to the bottom left hand corner of the window, in which case try fix number 2.

**Comment by iandol** [comment]
Value 1: still broken
Value 2: star map now is working fine! The problems I saw were the mouse cursor (the cross hair that tracks the system cursor) maps to a 1/4 of the screen (system cursor top right = middle of the screen). And in fullscreen mode the HUD and planet flickers (looks "interlaced"). Flicker is worse in some positions than others, facing the sun and it is bad enough to induce epilepsy!

**Comment by kanthoney** [comment]
Bugger!

From the command line again, try

    git checkout origin/issue_136

and try another build, then set the `issue_136_fix` value to `3`.

**Comment by iandol** [comment]
Value 3 (with commit 1667290) shows oolite in the bottom left quadrant:  

![screen shot 2015-05-12 at 00 34 03](https://cloud.githubusercontent.com/assets/153905/7577324/d2639e40-f83e-11e4-83b6-d224cd2db3cb.png)

**Comment by kanthoney** [comment]
OK then:

    git pull origin issue_136

Then build, and 

    defaults write org.aegidian.oolite issue_136_fix YES

**Comment by iandol** [comment]
So on commit 2d926abbd4ed72c5431327af1d9e88ed0c03d63f with YES as the defaults:

![screen shot 2015-05-12 at 09 46 04](https://cloud.githubusercontent.com/assets/153905/7583315/227eec2a-f88c-11e4-875a-543123416f9c.png)

But then I tried cycling through the other options again just in case and on value==1 it now seems to work!!!

![screen shot 2015-05-12 at 09 59 43](https://cloud.githubusercontent.com/assets/153905/7583511/df95e498-f88d-11e4-8f5e-fed2cdaed3e1.png)

Double checking the value:

```
>>  defaults read org.aegidian.oolite issue_136_fix     
1
```

**Comment by kanthoney** [comment]
Yay!  I'll take that!

By the way, I got the command wrong - it should have been

    defaults write org.aegidian.oolite key -bool YES

The issue you had with the truncated screen shots probably hasn't been fixed (I've just remembered about that).  Can you give that a try?

**Comment by iandol** [comment]
Screenshots are still truncated in windowed or full-screen mode, but system screen shots work fine so this isn't a major platform issue. Congrats on the fix!

**Comment by iandol** [comment]
I also tried switching to master and pulling the changes there and everything still works fine...

**Comment by kanthoney** [comment]
I think I've fixed the screenshot bug as well, so that's

    git checkout issue_136
    git pull origin issue_136
    defaults write org.aegidian.oolite key -bool YES

Thanks for the help!

**Comment by iandol** [comment]
Screenshots also fixed :-) :+1:

**Comment by kanthoney** [comment]
Fantastic!  Thanks again for all the help with that!
