### ISSUE TITLE
"concealment" parameter work incorrect in 1.84

### ISSUE THREAD

**Issue by AndSDev** [OoliteProject/oolite#201]
I am developing a package that adds the ability to explore the galaxy map.
It hides unexplored part of the galaxy, gradually showing new systems.

The package I am using parameter "concealment". Information about "concealment" parameter from forum: http://aegidian.org/bb/viewtopic.php?f=2&t=3231&start=1845#p240722

Link to package: http://12009.selcdn.ru/links/oolite/ZeroMap_0.4.oxz

The package is set:
- concealment 0 - for visited systems.
- concealment 100 - systems within 7LY.
- concealment 200 - systems within 10LY.
- concealment 300 - for all other systems.

**Problem 1**
For systems with concealment 200 is available the name of the planet.
![step1_r](https://cloud.githubusercontent.com/assets/13585370/17479609/2c8310a6-5d7c-11e6-8ee9-924508ea1946.png)

**Problem 2**
For concealment 100 is available a complete description of the planets (F7 screen). At 1.83 (1.83.0.6660-160130-10ca9e2) work correctly.
![step2_r](https://cloud.githubusercontent.com/assets/13585370/17479612/2f6a65da-5d7c-11e6-9bf4-46a6ad97d62d.png)
![step3](https://cloud.githubusercontent.com/assets/13585370/17479613/2f839c9e-5d7c-11e6-9f1e-5832c3b0ab1b.png)

**Comment by kanthoney** [comment]
It's probably my fault again.  I think the faulty commit is f9965400f3ca731578bcc66691a0d748a18ca696, which was a very messy merge commit, and I got the concealment stuff wrong.  I've pushed a new `concealment` branch which will hopefully fix the problem.

**Comment by AnotherCommander** [comment]
Problem 2 seems fixed but problem 1 apparently is still there.

**Comment by kanthoney** [comment]
The system name shouldn't now show up for concealed systems when they're targeted (on the concealment branch).

**Comment by AndSDev** [comment]
For (1): may be show name of system as "?????"?
P.S. Name also show if click on system and plot a route (on long range chart).

**Comment by AnotherCommander** [comment]
I think it looks good after commit 76ac517.

I would not put ???? as system name. It clutters the screen quite a bit IMO. I think the way it is now is fine,

**Comment by AndSDev** [comment]
Now tech level and etc (info) shows on map:
concealment 0 - full name, full info.
concealment 100 - full name, info as "???" (but some system have green or blue text).
concealment 200 - no name, no info. OK.

I'm tested current concealment branch - all problem are fixed.
But what means green or blue "???" text on systems witch concealment 100?

**Comment by kanthoney** [comment]
OK, I've merged into master.  Also puched a branch concealment-1.84 for merging into the maintenance branch if we want to do that.  This includes the fix in commit https://github.com/OoliteProject/oolite/commit/0c8573dd7a9d839386831581921818da73b9240d.

**Comment by AnotherCommander** [comment]
Yes, I believe we need to go ahead and import these fixes to the 1.84 maintenance branch, As for the ??? colors, I am not sure that the color variation was intended. Maybe this is a cosmetic bug that needs fixing too?

**Comment by kanthoney** [comment]
I think the question marks on the target system are supposed to be cyan while all the others are meant to be green.  I've seen the bug where they flicker between green and cyan as you move the chart around, but at the moment it seems to have spontaneously disappeared and I'm having trouble reproducing it.

**Comment by kanthoney** [comment]
Looks like there's nothing that sets the colour of the question marks, so they're in the same colour as the last thing drawn.  Depending on which planets you've concealed and where the chart is, that can be either cyan, green, or cyan for the target system and green for everything else.

**Comment by kanthoney** [comment]
I've fixed the colour for the question marks to be the usual chart label colour (yellow by default).

**Comment by AnotherCommander** [comment]
With the color fix in and the merge of all fixes to Maintenance, I think we should be good to close this. I'll do one last check in a few hours once I get home just to be sure and that should be it, I guess.

**Comment by AnotherCommander** [comment]
Hmm OK, I would not close it just yet. The chart interface now seems to be working as expected and that is fine. However, we still have an issue with contracts in the F4 screen, Check the pics below. They are from a new game at Lave, with the starting cargo contracts.
First is the standard one for a delivery to Maises:
![oolite-065](https://cloud.githubusercontent.com/assets/623526/17523944/ba8012ba-5e5c-11e6-8f4b-d2ac258bf285.jpg)
And then the same contract, with concealment applied:
![oolite-064](https://cloud.githubusercontent.com/assets/623526/17523963/d02edbbe-5e5c-11e6-918a-0e51df4cbb3c.jpg)

I do not mind at all having the name of an unexplored planet shown as contract destination or the red cross positioned in the exact destination's location. If anything, it is an incentive to go out there and explore. This is ok. But look at the distance in the second pic. It is wrong and seems to be pointing at about the edge of the known map (10LY). I think we should be seeing he actual correct distance to destination there. If you have an ANA and the first stop of the route is within the knonw planets, the name of the destination is shown wrong as well.

The above is my opinion and I welcome other points of view as well. The issue here can be considered fixed and I think that the inconsistency spotted was there since the first implementation of concealment.   Just need to agree on what we want to have shown in the contracts screen when concealment is in play.

**Comment by kanthoney** [comment]
The problem is [this line](https://github.com/OoliteProject/oolite/blob/master/src/Core/GuiDisplayGen.m#L1849):

```
target = [UNIVERSE findSystemNumberAtCoords:cursor_coordinates withGalaxy:galaxy_id includingHidden:NO];
```

Without that line `target` is set to `[PLAYER targetSystemID]`, which fixes the problem.  It might introduce others, of course.

**Comment by kanthoney** [comment]
Pushed that change to the resurrected concealment branch.

**Comment by AndSDev** [comment]
I like that in the description of the mission shows the destination point (after the mission will be marked with the concealment 100).

I would not want to show the part of the route to your destination - the system is hidden and the route is unknown. Show route within the visible part will be hint. If you build a route to a known part of the galaxy, it is built correctly without the unknown part.

**Comment by kanthoney** [comment]
I think `NONAME` should be `NOTHING` there, so it can locate systems that are only partly concealed if it needs to.

**Comment by AndSDev** [comment]
In Oolite exist several system with same coortdinates (in x, y):

G4: Riusbequ - Quzaarar [11,126]
G5: Zaenza - Lazaso [237,33]
G5: Divees - Tezabi [37,130]
G8: Gexequon - Edtizabe [244,169]
G8: Cecees - Esusale [94,96]

Call "findSystemNumberAtCoords" work correct? How can I understand this function, there may be problems.

P.S. same name in one galaxy:
G8 Inzaan : [73,174], [74,45]

**Comment by AnotherCommander** [comment]
Maybe a slightly better option would be to execute the target = ... line every time, but use the includingHidden parameter as dictated by concealment, i.e.:
```
target = [UNIVERSE findSystemNumberAtCoords:cursor_coordinates withGalaxy:galaxy_id includingHidden:concealment[target] >= OO_SYSTEMCONCEALMENT_NOTHING];
```
This seems to deal with the problem too and keeps the same logic as before in the unmodified game. Thoughts? I still have a feeling we are missing something here,

Oh, and in the contract descriptions, shouldn't the icons showing economy and governmet be absent when the system is concealed?

**Comment by kanthoney** [comment]
I've just pushed a change to hide the system icons in the description.  It was a javascript change - I don't think we've got access to the `OO_SYSTEMCONCEALMENT...` constants from there, so it's a hardcoded number at the moment.

I'm in favour of removing the offending line from GuiDisplayGen altogether. All it's doing is repeating something that's already been done in [`PlayerEntityControls.m`](https://github.com/OoliteProject/oolite/blob/master/src/Core/Entities/PlayerEntityControls.m#L2014), except it's also doing it in F4 when you don't want it to.

 The construct

```
if (concealment[target] < OO_SYSTEMCONCEALMENT_NONAME)
{
    target = [UNIVERSE findSystemNumberAtCoords:cursor_coordinates withGalaxy:galaxy_id includingHidden:NO];
}
```

is actually wrong, because `target` in the if clause isn't necessarily the same as the `target` you end up assigning - at least, not if the line is actually doing anything.

The difference between `YES` and `NO` is as follows.  For `NO`, as you move the cursor around the chart, the name of the nearest known system is displayed at the bottom of the chart.  For `YES`, if the nearest system is hidden then the name will be blank. I think the former is more correct.  If we remove the line altogether we get the same behaviour as for `NO` except the F4 chart isn't broken.

**Comment by AnotherCommander** [comment]
OK, sounds good, let's go with your suggestion, Kevin.
@AndSDev : Please let us know in case the solution proposed here gives you any sort of trouble.,

**Comment by AndSDev** [comment]
> If we remove the line altogether we get the same behaviour as for NO except the F4 chart isn't broken.
It sounds good. On F4 screen correctly shows the direct distance between the current and target system in any way.

**Comment by kanthoney** [comment]
Merged into master and maintenance.
